# Generated by Django 2.0.7 on 2018-07-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
    ]
