# Generated by Django 2.0.7 on 2018-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180727_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='radius',
            field=models.FloatField(default=0.5),
        ),
    ]
