# Generated by Django 2.0.7 on 2018-07-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180727_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='radius',
            field=models.FloatField(default=500),
        ),
    ]
