# Generated by Django 2.0.7 on 2018-07-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180727_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alert',
            field=models.BooleanField(default=True),
        ),
    ]
