# Generated by Django 2.0.7 on 2018-07-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.User'),
        ),
    ]
