# Generated by Django 2.0.7 on 2018-07-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20180731_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='sms_number',
        ),
    ]
