# Generated by Django 2.0.7 on 2018-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_1', models.CharField(max_length=300)),
                ('location_2', models.CharField(max_length=300)),
                ('location_3', models.CharField(max_length=300)),
                ('location_4', models.CharField(max_length=300)),
                ('location_5', models.CharField(max_length=300)),
            ],
        ),
    ]
