# Generated by Django 2.0.7 on 2018-07-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_number', models.CharField(blank=True, max_length=100)),
                ('location_1', models.CharField(blank=True, max_length=300)),
                ('location_2', models.CharField(blank=True, max_length=300)),
                ('location_3', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('radius', models.FloatField(default=5)),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
            ],
        ),
    ]
