# Generated by Django 2.0.7 on 2018-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('sms_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_4',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_5',
        ),
        migrations.AddField(
            model_name='device',
            name='sms_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_3',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
