# Generated by Django 2.0.7 on 2018-07-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial 18-11-06-458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
