# Generated by Django 2.0.7 on 2018-07-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180722_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('radius', models.FloatField(default=5)),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
            ],
        ),
    ]
