# Generated by Django 2.0.7 on 2018-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180723_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('location', models.CharField(max_length=300, null=True)),
                ('timestamp', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('radius', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_10',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_3',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_4',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_5',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_6',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_7',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_8',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location_9',
        ),
        migrations.RemoveField(
            model_name='user',
            name='radius',
        ),
    ]
