# Generated by Django 2.0.7 on 2018-07-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180723_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='device_id',
        ),
        migrations.AddField(
            model_name='location',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device'),
        ),
    ]
