# Generated by Django 2.0.7 on 2018-07-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180723_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.AddField(
            model_name='location',
            name='radius',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
