# Generated by Django 2.0.7 on 2018-07-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='location',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='devices.Device'),
        ),
    ]
