# Generated by Django 2.0.7 on 2018-07-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180725_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-timestamp',)},
        ),
    ]
