# Generated by Django 2.0.7 on 2018-07-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20180725_1601'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
    ]
