# Generated by Django 2.0.7 on 2018-07-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180727_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alert',
            field=models.BooleanField(default=True),
        ),
    ]
