# Generated by Django 2.0.7 on 2018-07-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='alert',
        ),
    ]
