# Generated by Django 2.0.7 on 2018-07-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='V1.Device')),
            ],
        ),
    ]
